### ISSUE TITLE
My Bluetooth can be detected but can't work

### ISSUE THREAD

**Issue by Qiuzeze** [inyan600/Dell-Inspiron-3670-Hackintosh#1]
@inyan600 Thank you very much for sharing your clover file. Most of my computer's features work fine. But Bluetooth can be detected, can't be used, the button to turn off Bluetooth is grayed out。Is your clover file recently updated? Thank you for sharing again.

**Comment by inyan600** [comment]
when I used macOS I didn't have any issues with bluetooth, but recently I've switched from macOS to Linux.

**Comment by phaibin** [comment]
Same issue, Bluetooth can't use.
